### ISSUE TITLE
Error: unable to resolve:

### ISSUE THREAD

**Issue by tutucoming** [deathmemory/FridaContainer#10]
您好，请问这个报错的原因是什么呢
<img width="1370" alt="image" src="https://github.com/deathmemory/FridaContainer/assets/82809880/609c4e89-10d1-4401-9f38-18f76c8f53ce">

**Comment by deathmemory** [comment]
可能是版本的问题，我把 `package-lock.json` 上传了。
我这边的版本号：
```
npm --version
6.4.1
```

**Comment by tangshunhui** [comment]
已经验证过下面方式有效:  https://nodejs.org/download/release/v12.22.12/
```
export PATH=/cygdrive/e/node-v12.22.12-win-x64:$PATH
npm install
npm run build
```

**Comment by tutucoming** [comment]
实测降低node版本至12.22.12有效

**Comment by deathmemory** [comment]
如果报上面的错误，可以执行：
```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --scripts-prepend-node-path=auto
```
来修复
