### ISSUE TITLE
你好，刚刚用了traceArtMethods这方法，发现不太对，求指导下

### ISSUE THREAD

**Issue by gtict112** [deathmemory/FridaContainer#2]
FCAnd.traceArtMethods(
    ['M:java.net.Socket'],
    {'java.net.Socket': {white: true, methods:['<init>']}},
        "match_str_show_stacks");

我想hook  socket里面的初始化函数，打印出来的log很奇怪
message: {'type': 'send', 'payload': '{"tid":29116,"status":"entry","tname":"spdy-0","classname":"java.lang.String","method":"public java.lang.String java.lang.String.toString()","method_":"toString","args":{}}'} data: None

感觉hook是java.lang.String  tostring方法

**Comment by deathmemory** [comment]
感谢提问，构造函数的 trace hook 当时调试时被我注释掉了，因为平时用着够用，所以忘记加回来了。今天晚些时候会提交更新，感谢！

**Comment by deathmemory** [comment]
增加构造函数的trace 代码已经提交了，请拉取最新的代码。`1fac5df058a414dcf557ab5a13255bcf8bff7607`
你可以这样调用：
```ts
// [5] trace java constructors
FCAnd.traceJavaMethods_custom(['E:java.net.URI'],
    {'java.net.URI': {white: true, methods: ['$init']}},
    "match_str_show_stacks");
```
这里保留的 frida 的 `$init` 表示构造函数，
祝顺利 :blush:
