### ISSUE TITLE
gson加载异常

### ISSUE THREAD

**Issue by rozbo** [deathmemory/FridaContainer#3]
现象是提示
> ERROR Error: java.lang.ClassNotFoundException: Didn't find class "com.google.gson.GsonBuilder" on path: DexPathList[[zip file "/data/data/com.mary.love/cache/gson.jar"],nativeLibraryDirectories=[/system/lib64]]

gson.jar 确实写入了目标位置
```
-rw-------  1 u0_a126 u0_a126_cache 240255 2021-04-07 20:38 gson.jar
```
怀疑`gson.jar`有误，尝试拖出来反编译，结果jar是正常的。
此时修改代码，
```ts
    const x =Java.openClassFile(dexpath); 
    x.load();
    console.log(x.getClassNames());
```
则直接提示异常
> ERROR Error: java.io.IOException: No original dex files found for dex location /data/data/com.mary.love/cache/gson.jar

安卓版本8.1。
不知道大佬可遇到此问题否？

**Comment by rozbo** [comment]
更新，已解决此问题。可能是高版本不能够加载jar的原因。可以使用https://github.com/r0ysue/AndroidSecurityStudy/blob/master/FRIDA/r0gson.dex.zip，替代的dex即可。

**Comment by deathmemory** [comment]
我用的测试系统也是 Android 8.1.0 pixel 2 没有遇到这个问题，会持续观察
感谢反馈。

**Comment by rozbo** [comment]
> 抱歉这么晚才看到，最近忙晕了
> 我用的测试系统也是 Android 8.1.0 pixel 2 没有遇到这个问题，会持续观察
> 感谢反馈。

那可就太神奇了，我们是同样的手机。
Pixel2 Android8.1.0，版本号`OPM 2.171026.006.G1`。
看来我分析的不对，你可再观察观察。
