### ISSUE TITLE
clone项目下来  没做任何改动，出现这个错误  但是307行什么都没有 重新build还是307行有问题，懵圈了

### ISSUE THREAD

**Issue by anylayer** [deathmemory/FridaContainer#4]
![image](https://user-images.githubusercontent.com/46556817/123072056-ca7eb480-d447-11eb-9370-cc56a457e973.png)
![image](https://user-images.githubusercontent.com/46556817/123072337-07e34200-d448-11eb-82ca-20f8121c8c7d.png)

**Comment by FreaxW** [comment]
![image](https://user-images.githubusercontent.com/46556817/123072516-34975980-d448-11eb-8104-1563aa014ffe.png)

**Comment by FreaxW** [comment]
会是358行几个点的问题吗

**Comment by deathmemory** [comment]
没有做任何改动吗？可我代码里这个方法的参数是写过类型声明的呀
![image](https://user-images.githubusercontent.com/4038034/123198674-1b41ec00-d4e0-11eb-9d6a-1006cf6157ad.png)
长这样子

**Comment by deathmemory** [comment]
你那边的类型声明怎么都不见了

**Comment by deathmemory** [comment]
语法错误，这个有点奇怪，难道是高版本的 node 做了什么改变吗？我的版本是 v14.15.4
