### ISSUE TITLE
修改 index.ts 引入 agent 目录下的类

### ISSUE THREAD

**Issue by aaeolus** [deathmemory/FridaContainer#5]
不知道如何修改 index.ts 来实时引入agent 目录写的frida脚本

**Comment by deathmemory** [comment]
在 agent 目录下创建类后，在Index.ts 里面写入类名 pycharm IDE 会有提示，直接按提示选择导入就行。
或者你可以手动引入类  `import {Classname} from "./agent/bb/ClassFile";`
需要注意的是，你创建的类，必须是可导出的，也就是 class 前面加 export

**Comment by aaeolus** [comment]
谢谢解答
