### ISSUE TITLE
Error TS2571: Object is of type 'unknown'.

### ISSUE THREAD

**Issue by Gordon0918** [deathmemory/FridaContainer#7]
clone下来之后，执行npm run build，错误如下：

> @dmemory/fridacontainer@1.0.9 build /Users/xinglizhen/Frida/FridaContainer
> frida-compile index.ts -o _fcagent.js

[TypeScript error: /Users/xinglizhen/Frida/FridaContainer/utils/FCAnd.ts(401,112): Error TS2571: Object is of type 'unknown'.] {
  fileName: '/Users/xinglizhen/Frida/FridaContainer/utils/FCAnd.ts',
  line: 401,
  column: 112,
  inputs: Set(105) {
    '/Users/xinglizhen/Frida/FridaContainer/index.ts',
    '/Users/xinglizhen/Frida/FridaContainer/utils/FCAnd.ts',
    '/Users/xinglizhen/Frida/FridaContainer/utils/FCCommon.ts',
    '/Users/xinglizhen/Frida/FridaContainer/utils/FCiOS.ts',
    '/Users/xinglizhen/Frida/FridaContainer/utils/dmlog.ts',
    '/Users/xinglizhen/Frida/FridaContainer/utils/repinning_test.js',
    '/Users/xinglizhen/Frida/FridaContainer/utils/android/Anti.ts',
    '/Users/xinglizhen/Frida/FridaContainer/utils/android/UnpinningPlus.js',
    '/Users/xinglizhen/Frida/FridaContainer/utils/android/jnimgr.ts',
    '/Users/xinglizhen/Frida/FridaContainer/utils/android/multi_unpinning.js',
    '/Users/xinglizhen/Frida/FridaContainer/utils/android/repinning.js',
    '/Users/xinglizhen/Frida/FridaContainer/utils/android/jni/method_data.ts',
    '/Users/xinglizhen/Frida/FridaContainer/utils/android/unpack/fridaUnpack.js',
    '/Users/xinglizhen/Frida/FridaContainer/utils/android/unpack/fridaUnpackSimply.js',
    '/Users/xinglizhen/Frida/FridaContainer/utils/common/StringUtils.ts',
    '/Users/xinglizhen/Frida/FridaContainer/utils/android/jni/jni_env.json',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/frida-gum/index.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/index.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/assert.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/globals.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/async_hooks.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/buffer.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/child_process.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/cluster.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/console.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/constants.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/crypto.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/dgram.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/dns.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/domain.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/events.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/fs.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/fs/promises.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/http.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/http2.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/https.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/inspector.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/module.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/net.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/os.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/path.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/perf_hooks.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/process.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/punycode.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/querystring.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/readline.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/repl.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/stream.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/string_decoder.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/timers.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/tls.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/trace_events.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/tty.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/url.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/util.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/v8.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/vm.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/wasi.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/worker_threads.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/zlib.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/@types/node/globals.global.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2018.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2017.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2016.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2015.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es5.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2015.core.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2015.collection.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2015.iterable.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2015.symbol.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2015.generator.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2015.promise.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2015.proxy.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2015.reflect.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2016.array.include.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2017.object.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2017.string.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2017.intl.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2017.typedarrays.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2018.asynciterable.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2018.asyncgenerator.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2018.promise.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2018.regexp.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2018.intl.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.esnext.intl.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2020.bigint.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.esnext.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2021.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2020.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2019.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2019.array.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2019.object.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2019.string.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2019.symbol.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2020.promise.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2020.sharedmemory.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2020.string.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2020.symbol.wellknown.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2020.intl.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2021.promise.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2021.string.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2021.weakref.d.ts',
    '/Users/xinglizhen/Frida/FridaContainer/node_modules/typescript/lib/lib.es2021.intl.d.ts'
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @dmemory/fridacontainer@1.0.9 build: `frida-compile index.ts -o _fcagent.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @dmemory/fridacontainer@1.0.9 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

请问这个怎么回事呢

**Comment by deathmemory** [comment]
因为没有执行 `npm install`
先执行它，再运行 build
