### ISSUE TITLE
默认的例子下出现报错 Error: unable to resolve

### ISSUE THREAD

**Issue by lyc8503** [deathmemory/FridaContainer#8]
一种 workaround 在这里提到了：https://github.com/frida/frida-compile/issues/59 降低 frida-compile 的版本

是否应该在项目中上传 package-lock.json 以防止每个人 npm i 得到的版本不同导致的问题？

同时也可能需要修改一下脚本适配新版本的 frida-compile

**Comment by deathmemory** [comment]
收到我跟进一下，多谢反馈

**Comment by deathmemory** [comment]
package-lock.json 已上传

**Comment by deathmemory** [comment]
如果报上面的错误，可以执行：
```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --scripts-prepend-node-path=auto
```
来修复
